### ISSUE TITLE
Occasional crash when pressing "again" or "good"

### ISSUE THREAD

**Issue by vegardholt** [lovac42/Fanfare#10]
Hello!

Sometimes when I press "again" or "good", Anki suddenly crashes.
I haven't notices a pattern to these crashes.'

This is the error log I get:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-06-09 19:15:41

Caught exception:
Traceback (most recent call last):
  File "aqt\reviewer.py", line 299, in <lambda>
  File "C:\Users\vegar\AppData\Roaming\Anki2\addons21\PassFail (EN)\__init__.py", line 35, in AKR_answerCard
    __oldFunc(self, ease)
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-30>", line 2, in _answerCard
  File "lib\site-packages\anki\hooks.py", line 666, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 663, in repl
  File "C:\Users\vegar\AppData\Roaming\Anki2\addons21\2073603704\fanfare.py", line 123, in affirm
    _old(r,ease)
  File "aqt\reviewer.py", line 270, in _answerCard
  File "C:\Users\vegar\AppData\Roaming\Anki2\addons21\864545277\review_controller.py", line 97, in wrapped
    originalResult = originalFunction(self)
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-32>", line 2, in nextCard
  File "lib\site-packages\anki\hooks.py", line 666, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 663, in repl
  File "C:\Users\vegar\AppData\Roaming\Anki2\addons21\2073603704\fanfare.py", line 129, in delayNextCard
    if self.state==REVIEW and self.checkLimitBreaker():
  File "C:\Users\vegar\AppData\Roaming\Anki2\addons21\2073603704\fanfare.py", line 157, in checkLimitBreaker
    self.recess.start(self.fb.audio_duration)
  File "C:\Users\vegar\AppData\Roaming\Anki2\addons21\2073603704\loots.py", line 135, in start
    mw.web.stdHtml(html, css='' if ANKI21 else mw.sharedCSS)
  File "aqt\webview.py", line 335, in stdHtml
TypeError: can only concatenate list (not "str") to list

**Comment by lovac42** [comment]
It sounds like you downloaded the old version on ankiweb or 2.1.15.
The new version on github hasn't been uploaed to ankiweb yet.
https://github.com/lovac42/Fanfare/releases

**Comment by vegardholt** [comment]
That would explain it. I'll try downloading the newer one. Thanks!
