### ISSUE TITLE
No Module Named AppKit

### ISSUE THREAD

**Issue by AlphaJace** [lovac42/Fanfare#2]
Hi. Really looking forward to using this addon but I keep getting an error.

Exception in thread /Users/Uswer/Library/Application Support/Anki2/addons21/2073603704/user_files/Silhouette/start/183619.wav:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "/Users/User/Library/Application Support/Anki2/addons21/2073603704/sound.py", line 18, in run
    playsound(self.getName())
  File "/Users/User/Library/Application Support/Anki2/addons21/2073603704/lib/playsound.py", line 57, in _playsoundOSX
    from AppKit     import NSSound
ModuleNotFoundError: No module named 'AppKit'

**Comment by lovac42** [comment]
It means your mac is missing the package AppKit. Do you know how to install it? I don't know mac, maybe try googling how.

Alternatively, you could just use mplayer. In sound.py, comment out lines 12, 21,23,24. Prefix with # on those lines. But your overall experience will be reduced as the lag time on mplayer is alot higher.

**Comment by AlphaJace** [comment]
Thanks for your quick reply man. I checked my "Python" folder and I oddly do seem to have AppKit installed (after playing with it earlier). However I still get the error. Also, I commented out the lines you told me and I'm still getting the same AppKit error. I wonder why my AppKit folder isn't being read...

**Comment by lovac42** [comment]
In that case it sounds like appkit isn't included in your system path. So lets try this, uncomment the changes there were made to sound.py. Instead edit lib/playsound.py and add this line to the top at line 2

import sys
sys.path.append("/home/me/appkit")

^ Put the actual path to appkit for your mac.

**Comment by AlphaJace** [comment]
No success with this lovac42. thank you for your continued help.

Debug info:
Anki 2.1.5 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Mac 10.14.1
Flags: frz=True ao=True sv=2

Exception in thread /Users/User/Library/Application Support/Anki2/addons21/2073603704/user_files/Silhouette/start/133054.wav:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "/Users/User/Library/Application Support/Anki2/addons21/2073603704/sound.py", line 18, in run
    playsound(self.getName())
  File "/Users/User/Library/Application Support/Anki2/addons21/2073603704/lib/playsound.py", line 57, in _playsoundOSX
    I never would have tried using AppKit.NSSound without seeing his code.
ModuleNotFoundError: No module named 'AppKit'

**Comment by lovac42** [comment]
Try replacing sound.py with this file: https://pastebin.com/raw/EQcSLy2D

Also move the lib folder to a temp location as well.

**Comment by AlphaJace** [comment]
It works!! Thank you! Definitely enjoy it after using it for a few cards. You've done a great job. One last question: how do you switch to Bruce Lee theme?

**Comment by lovac42** [comment]
You need to edit the config file using addon manager. Change theme to Bruce_Lee. It's in the readmes.

One thing though, you are now using mplayer, so yeah, if you experience any lag times, its mplayers fault, and not mine haha.

**Comment by AlphaJace** [comment]
Good news is that I don't experience any lag. Or maybe there is slight lag but it's not noticeable.
