### ISSUE TITLE
Error during break

### ISSUE THREAD

**Issue by Machern777** [lovac42/Fanfare#8]
Hello there!

First of all, thank you for this addon. It is exactly what I needed! I just found an issue: everytime I reach the break, an error window pops-up and I don't know what I should do to solve it. I tried changing the theme back to the original one, but it doesn't solve the problem. However, the rest of the sections work well: lapse, pass, reward, and start. I don't dare touch the code. Thank you!

This is the message I get:

> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-19 10:19:23

Caught exception:
Traceback (most recent call last):
  File "aqt\reviewer.py", line 296, in <lambda>
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-14>", line 2, in _answerCard
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 635, in repl
  File "C:\Users\Redd\AppData\Roaming\Anki2\addons21\2073603704\fanfare.py", line 123, in affirm
    _old(r,ease)
  File "aqt\reviewer.py", line 268, in _answerCard
  File "C:\Users\Redd\AppData\Roaming\Anki2\addons21\864545277\review_controller.py", line 97, in wrapped
    originalResult = originalFunction(self)
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-16>", line 2, in nextCard
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 635, in repl
  File "C:\Users\Redd\AppData\Roaming\Anki2\addons21\2073603704\fanfare.py", line 129, in delayNextCard
    if self.state==REVIEW and self.checkLimitBreaker():
  File "C:\Users\Redd\AppData\Roaming\Anki2\addons21\2073603704\fanfare.py", line 157, in checkLimitBreaker
    self.recess.start(self.fb.audio_duration)
  File "C:\Users\Redd\AppData\Roaming\Anki2\addons21\2073603704\loots.py", line 135, in start
    mw.web.stdHtml(html, css='' if ANKI21 else mw.sharedCSS)
  File "aqt\webview.py", line 352, in stdHtml
TypeError: can only concatenate list (not "str") to list

**Comment by rodrimix99** [comment]
I'm getting the same exact error every time I get into a break, do you know if it also happens when getting the award?

**Comment by Machern777** [comment]
> I'm getting the same exact error every time I get into a break, do you know if it also happens when getting the award?

The reward works fine. It is just the break that gives me an error message.

**Comment by lovac42** [comment]
Are you using the Ankiweb version? I haven't updated that, it is a 50mb upload.
This is the latest version, drag and drop to addon manager.
https://github.com/lovac42/Fanfare/releases

**Comment by Machern777** [comment]
@lovac42 No, I'm using the desktop version. I'll do that, but I don't know how. I tried dragging the address you shared, but Anki only lets me add codes. Thanks in advance!
